apiVersion: v1
kind: Service
metadata:
  name: ms3-service
spec:
  selector:
    app: ms3
  type: NodePort
  ports:
    - port: 8030
      targetPort: 8030
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms3-deployment
spec:
  selector:
    matchLabels:
      app: ms3
  replicas: 1
  template:
    metadata:
      labels:
        app: ms3
    spec:
      containers:
      - name: ms3
        image: dev4java11/ms3:latest
        ports:
        - containerPort: 8030
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: production
                key: app_profile
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: production
