apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-scripts-pv
  labels:
    type: local
    app: mariadb
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/mariadb/scripts"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-scripts-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
